### ISSUE TITLE
LSP-Grammarly can't find Node Runtime

### ISSUE THREAD

**Issue by luispuerto** [sublimelsp/LSP-Grammarly#26]
I tried with hombrew and it fails: 

```
{
  "command": [
    "/opt/homebrew/opt/node@16/bin/node",
    "${server_path}",
    "--stdio"
  ]
}
```
<img width="372" alt="Screenshot 2024-01-07 at 11 05 50" src="https://github.com/sublimelsp/LSP-Grammarly/assets/22882880/765c5e55-2935-4976-a4d1-0f15bcbb202d">

```
Unable to start subprocess for grammarly
Traceback (most recent call last):
  File "/Users/luispuerto/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 250, in start_async
    if plugin_class.needs_update_or_installation():
  File "/Users/luispuerto/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/Users/luispuerto/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/npm_client_handler.py", line 130, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "/Users/luispuerto/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/server_npm_resource.py", line 49, in create
    raise Exception('Failed resolving Node.js Runtime. Please see Sublime Text console for more information.')
Exception: Failed resolving Node.js Runtime. Please see Sublime Text console for more information.

```

PS1/ I'm on macOS… so I really know what is going on with `  File "/Users/luispuerto/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 250, in start_async`. 
PS2/ Node16 is correctly installed

<img width="506" alt="image" src="https://github.com/sublimelsp/LSP-Grammarly/assets/22882880/188e0103-4909-4839-bf0d-64a7672b998c">

_Originally posted by @luispuerto in https://github.com/sublimelsp/LSP-Grammarly/issues/23#issuecomment-1880012904_

**Comment by luispuerto** [comment]
I also don't know how I can customize settings on the LSP Utils that I have seen some people is able to…

**Comment by troyane** [comment]
I have exactly the same issue. Node was installed via brew (`brew install node`) and works well
```bash
node -v v21.7.2
```

Do you have any clue how I could set it all up?

**Comment by luispuerto** [comment]
The API this package was using is deprecated by grammarly ;)

**Comment by luispuerto** [comment]
I'm closing here
